repository:
  name: 'aaronfagan'
  description: 'Github Profile Readme'
  homepage: 'https://www.aaronfagan.ca/'
  default_branch: 'main'
  private: false
  has_issues: false
  has_wiki: false
  has_downloads: false
  has_projects: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
